import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ChatsBar from "@/comp/ChatsBar";
import { SidebarProvider } from "./context/sidebarContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="cont">
        <SidebarProvider>
          <ChatsBar/>
          {children}
        </SidebarProvider>

        </div>
        </body>
    </html>
  );
}
